export const ALTS: Record<string, string> = {
  '/foods/fruit_pome.webp': 'Pome fruit',
  '/foods/fruit_citrus.webp': 'Citrus fruit',
  '/foods/fruit_stone.webp': 'Stone fruit',
  '/foods/fruit_tropical.webp': 'Tropical fruit',
  '/foods/fruit_berry.webp': 'Berry',
  '/foods/veg_leafy.webp': 'Leafy vegetable',
  '/foods/veg_cruciferous.webp': 'Cruciferous vegetable',
  '/foods/veg_root.webp': 'Root vegetable',
  '/foods/veg_nightshade.webp': 'Nightshade vegetable',
  '/foods/veg_squash.webp': 'Squash and gourds',
  '/foods/veg_fungi.webp': 'Mushrooms',
  '/foods/veg_allium.webp': 'Allium',
  '/foods/herb_fresh.webp': 'Fresh herb',
  '/foods/grain_rice.webp': 'Rice',
  '/foods/grain_pasta.webp': 'Pasta',
  '/foods/grain_bread.webp': 'Bread',
  '/foods/grain_flatbread.webp': 'Flatbread',
  '/foods/grain_pastry.webp': 'Pastry',
  '/foods/grain_cereal.webp': 'Cereal',
  '/foods/starch_potato.webp': 'Potato',
  '/foods/meat_poultry.webp': 'Poultry',
  '/foods/meat_red_raw.webp': 'Red meat',
  '/foods/meat_red_processed.webp': 'Processed red meat',
  '/foods/seafood_fish.webp': 'Fish',
  '/foods/seafood_shellfish.webp': 'Shellfish',
  '/foods/protein_egg.webp': 'Egg',
  '/foods/protein_plant.webp': 'Plant protein',
  '/foods/legume_bean.webp': 'Bean or legume',
  '/foods/dairy_milk.webp': 'Milk',
  '/foods/dairy_cheese_hard.webp': 'Hard cheese',
  '/foods/dairy_cheese_soft.webp': 'Soft cheese',
  '/foods/dairy_yogurt.webp': 'Yogurt',
  '/foods/dairy_fat.webp': 'Butter or cream',
  '/foods/fat_oil.webp': 'Cooking oil',
  '/foods/nut_seed.webp': 'Nut or seed',
  '/foods/condiment_sauce.webp': 'Sauce or dressing',
  '/foods/condiment_spice.webp': 'Spice',
  '/foods/baking_sweet.webp': 'Sweet baking ingredient',
  '/foods/baking_dry.webp': 'Dry baking ingredient',
  '/foods/snack_salty.webp': 'Salty snack',
  '/foods/snack_sweet.webp': 'Sweet snack',
  '/foods/meal_soup.webp': 'Soup',
  '/foods/meal_prepared.webp': 'Prepared meal',
  '/foods/bev_water.webp': 'Water',
  '/foods/bev_coffee_tea.webp': 'Coffee and tea',
  '/foods/bev_soda_juice.webp': 'Soft drinks and juice',
  '/foods/bev_alcohol.webp': 'Alcoholic drink',
  '/foods/other.webp': 'Miscellaneous food',

  '/nutrition-highlights/balance.webp': 'Electrolyte balance',
  '/nutrition-highlights/fat.webp': 'Fat Quality',
  '/nutrition-highlights/fiber.webp': 'Dietary fiber',
  '/nutrition-highlights/fiber2.webp': 'Dietary fiber',
  '/nutrition-highlights/gut-health.webp': 'Gut health',
  '/nutrition-highlights/micronutrients.webp': 'Vitamins and minerals',
  '/nutrition-highlights/protective.webp':
    'Protective phytonutrients and antioxidants',
  '/nutrition-highlights/protein.webp': 'Protein',
  '/nutrition-highlights/protein2.webp': 'Protein',
  '/nutrition-highlights/satiety.webp': 'Satiety and fullness',
  '/nutrition-highlights/salt2.webp': 'Sodium and salt',
  '/nutrition-highlights/sugar.webp': 'Sugar',
  '/nutrition-highlights/whole.webp': 'Processing level',
};
